#!/usr/bin/env bash
. library.sh
curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@$HOST_MACHINE:5984/_global_changes
curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@$HOST_MACHINE:5984/_replicator
curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@$HOST_MACHINE:5984/_users
curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@$HOST_MACHINE:5984/cats
curl -X PUT http://$COUCHDB_USER:$COUCHDB_PASSWORD@$HOST_MACHINE:5984/catsconfig