version: '3.9'
services:
        zookeeper:
                image: zookeeper
                restart: always
                ports:
                        - 2181:2181
                        - 2888:2888
                        - 3888:3888
                        - 8080:8080
                environment:
                        ZOO_MY_ID: 3
                        ZOO_SERVERS: server.1=192.168.1.35:2888:3888;2181 server.2=192.168.1.21:2888:3888;2181 server.3=192.168.1.28:2888:3888;2181