services:
        zookeeper:
                container_name: zookeeper-1
                image: bitnami/zookeeper
                restart: always
                ports:
                        - 2181:2181
                        - 2888:2888
                        - 3888:3888
                        - 8080:8080
                volumes:
                        - d:/zookeeper:/bitnami/zookeeper
                environment:
                        ALLOW_ANONYMOUS_LOGIN: "true"
                        ZOO_SERVER_ID: 1
                        ZOO_SERVERS: windowsserver.broadband:2888:3888
        kafka:
                container_name: kafka-1
                image: bitnami/kafka
                restart: always
                ports:
                        - 9092:9092
                volumes:
                        - d:/kafka:/bitnami/kafka
                depends_on:
                        - zookeeper
                environment:
                        KAFKA_BROKER_ID: 1
                        KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
                        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
                        KAFKA_CFG_ZOOKEEPER_CONNECT: windowsserver.broadband:2181
                        ALLOW_PLAINTEXT_LISTENER: "true"