services:
        zookeeper:
                container_name: zookeeper-1
                image: bitnami/zookeeper
                restart: always
                ports:
                        - 2181:2181
                        - 2888:2888
                        - 3888:3888
                        - 8080:8080
                environment:
                        ALLOW_ANONYMOUS_LOGIN: "true"
                        ZOO_SERVER_ID: 1
                        ZOO_SERVERS: 192.168.1.28:2888:3888