#!/usr/bin/env bash
. library.sh
export KAFKA_BROKER_ID
export KAFKA_CFG_LISTENERS
export KAFKA_CFG_ADVERTISED_LISTENERS
export KAFKA_CFG_ZOOKEEPER_CONNECT
export ALLOW_PLAINTEXT_LISTENER
export KAFKA_CFG_DELETE_TOPIC_ENABLE
docker run --name $KAFKA_CONTAINER_NAME -d --rm -p 9092:9092 -v $KAFKA_STORAGE_VOLUME:/bitnami/kafka -e KAFKA_BROKER_ID -e KAFKA_CFG_LISTENERS -e KAFKA_CFG_ADVERTISED_LISTENERS -e KAFKA_CFG_ZOOKEEPER_CONNECT -e ALLOW_PLAINTEXT_LISTENER -e KAFKA_CFG_DELETE_TOPIC_ENABLE bitnami/kafka:latest